# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('hash_address', models.CharField(max_length=40)),
            ],
        ),
    ]
