# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='falcon_app.User'),
            preserve_default=False,
        ),
    ]
